Velocidex/go-ntfs

- .gitignore
- attribute.go
- bin/stat.go
- fixtures/TestNTFS.golden
- go.mod
- go.sum
- i30.go
- mft.go
- model.go
- ntfs.go
- ntfs_test.go
References: https://github.com/williballenthin/INDXParse
> Implement I30 carving.

- parser/easy.go
Previously they were taken from the $FILE_NAME attribute but that does
not change if the file is modified.
> NTFS Info times should be taken from $STANDARD_INFORMATION

- parser/easy.go
Previously we emitted an inode on each of the filenames of an MFT
entry. This is confusing because both refer to the same file. However
malicious users may rename the short file name to something different
and most tools only show the long file name. The risk is that a user
may discover a reference to a file but not be able to find the file -
thinking it was removed. Actually the file may exist but will have a
LFN different from the short file name it sees.
This change hides the short file name if it contains a ~ which is
usually the case for normal files. If a reference is found to a file
with a ~ in it the user may expect this to be a short file name
anyway. So it removed confusion. But in the common case the short file
names are not relevant.
> Combine files with long and short file names

- parser/attribute.go
- parser/context.go
- parser/easy.go
Some files have an initialized_size < actual_size which implies the
runlist should be padded after initialized_size with 0s.
> Fixed a bug in attribute reader

- bin/mft.go
- go.mod
- go.sum
- parser/boot.go
- parser/context.go
- parser/mft.go
This allows one to parse all the mft entries from the single $MFT file
itself without needing the entire image.
One can then go back to the image and extract the mft entries of
interest only.
> Added command to dump out highlight from an $MFT file.

- parser/helpers.go
Improving the precision of  SI and FN attributes to its actual resolution in NTFS which is 100 nanoseconds counting from Jan 1, 1601.
> more precise (nanosecond) timestamp for SI and FN fields.

- parser/attribute.go
Fixes a bug where a 64 bit value was casted to int, potentially
resulting in a negative value that would then cause a panic
due to it being used in a slice expression.
To reproduce: Try reading a very large file (e.g. pagefile.sys) on a 32-bit Windows.
> Fix a potential out of range bug when reading on 32-bit systems

- go.sum
- parser/attribute.go
- parser/attribute_test.go
- parser/boot.go
- parser/easy.go
- parser/fixtures/TestNTFS.golden
- parser/i30.go
- parser/mft.go
- parser/ntfs_gen.go
- parser/reader.go
Also ignore EOF errors from the reader which may come from short reads
at the end of the disk.
Add I30 parsing for INDEX_ROOT as well when scanning for I30 node.
> Ignore fixup errors.

- parser/boot.go
Fix a bug where a corrupt MFT entry could lead to a panic from
an out of bounds array access.
> Fix a possible panic with corrupt MFT entries.

- parser/attribute.go
- parser/debug.go
- parser/mft.go
Resolving ATTRIBUTE_LIST recursively could get into a recursive loop.
Fixes: #29
> Fix possible recursion bug.

- parser/easy.go
- parser/mft.go
When MFT parsing encounters an ADS it duplicates the row - the ADS row
should
1. Be considered as a file not a directory (IsDir = false)
2. Size should reflect the size of the ADS not the host entry.
> MFT analysis bug fix

- parser/context.go
- parser/reader.go
- parser/usn.go
This resulted in a bug where watch_usn() was unable to emit new rows
after a while.
> Purge ntfs context caches to ensure each watch USN pass has new data

- bin/test_filename.go
- parser/boot.go
- parser/context.go
- parser/mft.go
- parser/model.go
- parser/reader.go
- parser/utils.go
- tests/usn_with_two_vcns/fixtures/stat.golden
Sometimes when reconstructing MFT paths we hit errors (especially for unallocated entried). The previous code would just stop the path reconstruction at the point of error and since paths are built in reverse it would appear like the last valid directory is actually rooted at the top of the filesystem.
This change creates special "psuedo" directories where these paths can terminate making it clear that they are errors. We also add extra components describing the error of why we were unable to continue processing.
> Added error reporting when reconstructing the path

- bin/stat.go
- parser/context.go
- parser/hardlinks.go
- parser/mft.go
- parser/model.go
- parser/options.go
- parser/usn.go
Also enable optional short file name analysis and options to be set on ntfs context
> Match USN parent MFT sequence when reconstructing paths.

- parser/hardlinks.go
- parser/mft.go
- parser/options.go
- parser/usn.go
This is helpful when prepending the drive letter to calculated paths.
> Allow a prefix to be specified in the NTFS Options.

- bin/check.go
- bin/runs.go
- parser/attribute.go
- parser/boot.go
- parser/context.go
- parser/debug.go
- parser/easy.go
- parser/mft.go
- parser/reader.go
- parser/runs.go
- tests/large_file_small_init/fixtures/runs.golden
- tests/usn_with_two_vcns/fixtures/runs.golden
When the MFT is too large to fix in one entry, the second $DATA stream
VCN is stored in another MFT entry and an ATTRIBUTE_LIST points to
it. There was a bug where the second VCN was added without applying
suitable fixups and therefore the runlist was sometimes corrupted.
This PR adds more debugging and visibility to allow tracking the
physical sector on the disk where a file resides. There is also a
"check" command added to run a host of sanity checks. Currently we check
that the MFT ID we try to open is the same one we receive.
> Fixed bug in large MFT support.

- parser/easy.go
For some unknown reason, the `Stat()` function in easy.go was not using the MFT header flag to determine if an entry represents a directory. Instead it was setting an entry to be a directory if it had an INDEX_ROOT or INDEX_ALLOCATION attribute, which is not guaranteed to be correct. Usually the INDEX_* entries are $I30 streams, but not always, such as in the case of $SDS file (which does not have $I30 streams but has $SDH and $SDI streams which are INDEX_* type).
This has now been fixed to just use the MFT header flag, which is the definitive source. With this change, the Velociraptor project will no longer need special treatment for fetching $SDS files, ie, no need for Windows.Triage.SDS.
> Fix incorrect dir detection

- bin/live.go
- parser/attribute.go
- parser/easy.go
This avoids considering $Boot as sparse.
> Only decode sparse runs for sparse files.

- parser/attribute.go
Fixes: https://github.com/Velocidex/velociraptor/issues/2956
> Prevent overflow when runlist is corrupted.

- parser/usn.go
Small typo in the `SourceInfo()` function not returning the correct values
> Fix typo in SourceInfo()

- bin/usn.go
- parser/caching.go
- parser/context.go
- parser/easy.go
- parser/hardlinks.go
- parser/mft.go
- parser/model.go
- parser/usn.go
- parser/utils.go
When reconstructing USN journal paths we actually have access to more information than contained in the MFT because the USN journal records partial filename information. This PR adds the ability to preload these partial file information in case they are encounterd during path reconstruction.
See https://cybercx.com.au/blog/ntfs-usnjrnl-rewind/ for more details.
> Refactor path resolution to allow preloading of MFTEntrySummary

- parser/attribute.go
When a partial read occurs and io.EOF is returned, the file_offset or buf_idx does not advance. This appears to cause errors such as issue #71 in go-ntfs. It would be great if you could check this.
> Fix: n is not used in case of io.EOF

- .github/workflows/go.yml
- parser/reader.go
- parser/reader_test.go
This PR addresses an issue in the PagedReader that can lead to an infinite loop at the end of a file, eventually causing an out-of-memory condition. The problem occurs because, in some cases, the code invoking the PagedReader cannot reliably detect when the end of the file has been reached. This behavior can be reproduced using the Velociraptor query below.
```
SELECT * FROM parse_jsonl(filename='''C:\test\test.jsonl''', accessor='raw_file')
```
Rendered pprof CPU profile:
> Fix reading beyond the end of a file

- parser/boot.go
- parser/handwritten.go
- parser/reader.go
- parser/reader_test.go
- parser/usn.go
Previous EOF semantic is not workable because an err != nil is still given even though there is valid data forcing callers to distinguish between err != nil && err != EOF to specifically rule out EOF as an actual error.
The new semantics are:
1. Reading anywhere within the file (even if the buffer falls outside the file) will return n = len(buf) and err = 0
2. reading outside the bounds of the file will return n=0 and err = EOF
> Changed semantics of the reader again
